# Generated by Django 4.2.7 on 2023-11-16 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('account_type', models.CharField(max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Flyer', models.TextField(max_length=3000, null=True)),
                ('Description', models.TextField(max_length=1000)),
                ('Artists', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=20)),
                ('Time', models.TimeField(null=True)),
                ('Address', models.CharField(default='Default Address', max_length=255)),
                ('City', models.CharField(default='Default City', max_length=255)),
                ('State', models.CharField(default='Default State', max_length=255)),
                ('ZipCode', models.CharField(default=12345, max_length=255)),
                ('Venue', models.CharField(max_length=255)),
                ('Price', models.CharField(max_length=255, null=True)),
                ('IsAllAges', models.BooleanField()),
                ('Link', models.TextField(max_length=2000, null=True)),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saved_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
