# Generated by Django 4.2.7 on 2023-11-16 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_event_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='event',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
