# Generated by Django 4.2.7 on 2023-11-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_event_saved_by_event_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved_events',
            field=models.ManyToManyField(blank=True, related_name='users_who_saved', to='database.event'),
        ),
    ]
