# Generated by Django 4.2.7 on 2023-11-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_wesbite_customuser_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Created_By_Email',
            field=models.CharField(default='user@user.com', max_length=255),
        ),
    ]
